### ISSUE TITLE
Storybook Deployment

### ISSUE THREAD

**Issue by NjohPrince** [World-Charity-Tour/camsol-components#4]
Storybook deployment on GitHub pages.

@lowesilvan please since you are to handle this, please configure the build path to point to the /docs directory. @devsecur did some updates as needed.

**Comment by devsecur** [comment]
https://github.com/mmistakes/minimal-mistakes/discussions/3671

do we have to setup a theme?

**Comment by NjohPrince** [comment]
> https://github.com/mmistakes/minimal-mistakes/discussions/3671
> 
> do we have to setup a theme?

Do you mean a custom storybook theme for Camsol?

**Comment by lowesilvan** [comment]
@NjohPrince The storybook deployment is setup at [https://World-Charity-Tour.github.io/camsol-components/]( https://World-Charity-Tour.github.io/camsol-components/)
So I think we can close this issue if nothing else

**Comment by NjohPrince** [comment]
Thank you very much @lowesilvan
